[general]
library_name = "LibLSE"
output_file_path = "LibLSE.jl/LibLSE.jl"
module_name = "cLSE"
jll_pkg_name = ""
export_symbol_prefixes = ["lse_"]
use_julia_native_enum_type = true
print_using_CEnum = false
output_ignorelist = []
auto_mutability = false
clang_args = ["-O2"]

[codegen]
use_ccall_macro = true
wrap_variadic_functions = false
function_wrapper_options.wrap_cdecl = false
function_wrapper_options.wrap_stdcall = false
output_mode = "single"
